language: python

sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3.5"
  - "nightly"

install:
  - pip install --upgrade pip setuptools wheel pytest
  - pip install -r requirements-dev.txt
  - pip install --editable .

script:
  - pip freeze --all
  - pytest --cov=johnnydep

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
