language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3.5"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install --upgrade pip setuptools wheel pytest
  - pip install -r requirements-dev.txt
  - pip install --editable .

script:
  - pip freeze --all
  - pytest --cov=johnnydep

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
