language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3.5"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"

install:
  - pip install -r requirements-dev.txt
  - pip install --editable .
  - pip install --upgrade setuptools wheel pytest

script:
  - pip freeze --all
  - pytest --cov=johnnydep

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
