language: python

sudo: false

python:
  - "2.7"
  - "3.8"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"

install:
  - pip install --upgrade pip setuptools wheel pytest
  - pip install -r requirements-dev.txt --use-feature=2020-resolver

script:
  - pip freeze --all
  - pytest --cov=johnnydep

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
