from textwrap import dedent

from johnnydep.lib import JohnnyDist


def test_dot_export(make_dist):
    deps = ["child>0.1"]
    extras = {"x": ["extra"]}
    make_dist(name="parent", install_requires=deps, extras_require=extras)
    make_dist(name="child")
    make_dist(name="Extra")
    dist = JohnnyDist("parent[x]")
    actual = dist.serialise(format="dot")
    expected = dedent(
        """
        # generated by https://github.com/wimglenn/johnnydep
        digraph parent {
            "parent[x]";
            "child";
            "Extra";
            "parent[x]" -> "child" [label=">0.1"];
            "parent[x]" -> "Extra";
        }
        """
    ).strip()
    assert actual == expected
